site_name: laminas-config-aggregator
docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: intro.md
    - 'Config Providers': config-providers.md
    - 'Post Processors': config-post-processors.md
    - Caching: caching.md
site_description: 'Lightweight library for collecting and merging configuration from different sources.'
repo_url: 'https://github.com/laminas/laminas-config-aggregator'
extra:
    project: Components
    project_url: 'https://docs.laminas.dev'
